### ISSUE TITLE
Failed to load Discord RPC lib (126)

### ISSUE THREAD

**Issue by Unknown025** [Jimmacle/discord-rpc.net#3]
After finally managing to compile a DLL for .NET 4.5.2 instead of .NET Core 2, the DLL throws the exception "System.TypeLoadException: 'Failed to load Discord RPC lib from discord-rpc.dll: 126'" during loading (every single time it seems). I'll see if I can find a work around.

**Comment by Unknown025** [comment]
#4 Fixed the issue, sent pull request.

**Comment by Jimmacle** [comment]
Merged #5 .
